# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [34]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in c:\Users\11791\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\Users\11791\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\11791\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\11791\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\11791\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [36]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [37]:
# Count by hand. (lol kidding)

len(df_food)

125

In [38]:
# Try to print or display it nicely.

df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [39]:
# Show the column names and their types.
df_food.dtypes

GPA                                 str
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                        str
comfort_food_reasons                str
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                        str
diet_current_coded                int64
drink                           float64
eating_changes                      str
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                   str
fav_cuisine                         str
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                      str
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                        str
ideal_diet                          str
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend                 str
mother_education                float64
mother_profession                   str
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                         str
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                              str
dtype: object

In [40]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
pd.DataFrame(df_food.dtypes)

                                    0
GPA                               str
Gender                          int64
breakfast                       int64
calories_chicken                int64
calories_day                  float64
calories_scone                float64
coffee                          int64
comfort_food                      str
comfort_food_reasons              str
comfort_food_reasons_coded    float64
cook                          float64
comfort_food_reasons_coded.1    int64
cuisine                       float64
diet_current                      str
diet_current_coded              int64
drink                         float64
eating_changes                    str
eating_changes_coded            int64
eating_changes_coded1           int64
eating_out                      int64
employment                    float64
ethnic_food                     int64
exercise                      float64
father_education              float64
father_profession                 str
fav_cuisine                       str
fav_cuisine_coded               int64
fav_food                      float64
food_childhood                    str
fries                           int64
fruit_day                       int64
grade_level                     int64
greek_food                      int64
healthy_feeling                 int64
healthy_meal                      str
ideal_diet                        str
ideal_diet_coded                int64
income                        float64
indian_food                     int64
italian_food                    int64
life_rewarding                float64
marital_status                float64
meals_dinner_friend               str
mother_education              float64
mother_profession                 str
nutritional_check               int64
on_off_campus                 float64
parents_cook                    int64
pay_meal_out                    int64
persian_food                  float64
self_perception_weight        float64
soup                          float64
sports                        float64
thai_food                       int64
tortilla_calories             float64
turkey_calories                 int64
type_sports                       str
veggies_day                     int64
vitamins                        int64
waffle_calories                 int64
weight                            str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [41]:
# Remove ‘em.
df_food_col_subset = df_food[["Gender", "calories_day", "weight"]]
df_food_col_subset.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

In [42]:
# Is there a second way to remove columns?

common = ["Gender", "calories_day", "weight"]
selected_column = df_food.columns.intersection(common)

df_food_col_subset2 = df_food[selected_column]
df_food_col_subset2.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

In [43]:
# 🚀 Extra credit: What about a third way to remove columns?

df_food_col_subset3 = df_food.loc[:, ["Gender", "calories_day", "weight"]]
df_food_col_subset3.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

What about `NaN`s? How many are there?

In [44]:
# Count ‘em.

df_food_col_subset.isnull().sum()

Gender           0
calories_day    19
weight           2
dtype: int64

In [45]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

nice_frame = pd.DataFrame(df_food_col_subset.isnull().sum())
nice_frame.columns = ["Sum of null"]
nice_frame

              Sum of null
Gender                  0
calories_day           19
weight                  2

In [46]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [47]:
# Drop ‘em in-place.

df_food_col_subset.dropna(inplace=True)
df_food_col_subset.head()

   Gender  calories_day                    weight
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190
5       1           3.0                       190

In [48]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

df_food.head()
print(df_food.isnull().sum())

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [49]:
# Fix that in-place.

# df_food_col_subset.weight.value_counts()
df_food_col_subset["weight"] = pd.to_numeric(df_food_col_subset["weight"], errors="coerce")
df_food_col_subset.dropna(inplace=True)

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [50]:
# Savey save!

cleaned_data = df_food_col_subset.copy()
cleaned_data.head()
cleaned_data.to_csv("../data/cleaned_food.csv", index=False)

In [51]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

with open ("../data/cleaned_food.csv", "r") as file:
    for i in range(5):
        print(file.readline().strip())

Gender,calories_day,weight
1,3.0,155.0
1,2.0,190.0
1,3.0,190.0
2,3.0,180.0

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [52]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

df_salary = pd.read_csv("../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv", sep="\t")
df_salary.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [53]:
# Count by hand. I’m dead serious.

len(df_salary)

28062

What are the columns and their types?

In [54]:
# Show the column names and their types.

df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [55]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_salary.columns = ['timestamp', 'age', 'industry', 'title', 'title_context', 'salary', 'additional_compensation', 'currency', 'other_currency', 'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe', 'highest_education_completed','gender', 'race']
df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [56]:
# List the unique industries and a count of their instances.

df_salary.industry.value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [57]:
# Filtery filter.

selected_industry = ["Computing or Tech", "Education (Higher Edurcation)", "Nonprofits", "Health care", "Government and Public Administration"]

df_salary_tech = df_salary[df_salary["industry"].isin(selected_industry)]
df_salary_tech.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
10,4/27/2021 11:03:03,25-34,Nonprofits,Office Manager,NaN,"47,500",0.0,USD,NaN,NaN,United States,NaN,"Boston, MA",5-7 years,5-7 years,College degree,Woman,White
14,4/27/2021 11:03:11,18-24,Health care,Patient care coordinator,NaN,"32,000",NaN,CAD,NaN,NaN,Canada,NaN,Remote,1 year or less,1 year or less,College degree,Woman,White

Do a sanity check by counting.

In [58]:
# Sanity check count.

print(len(df_salary))
print(len(df_salary_tech))

28062
10903

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [59]:
# Filtery filter (in place) for just the jobs that pay in USD!

df_salary_tech = df_salary_tech[df_salary_tech["currency"] == "USD"]
df_salary_tech

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
10,4/27/2021 11:03:03,25-34,Nonprofits,Office Manager,NaN,"47,500",0.0,USD,NaN,NaN,United States,NaN,"Boston, MA",5-7 years,5-7 years,College degree,Woman,White
20,4/27/2021 11:03:24,25-34,Health care,Data Programmer Analyst,NaN,"74,000",0.0,USD,NaN,NaN,USA,Pennsylvania,Philadelphia,5-7 years,5-7 years,Master's degree,Woman,White
21,4/27/2021 11:03:24,35-44,Nonprofits,Program Coordinator & Assistant Editor,NaN,"50,000",NaN,USD,NaN,NaN,United States,NaN,Atlanta,5-7 years,2 - 4 years,PhD,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [60]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

df_salary_tech.country.value_counts()

country
United States     3496
USA               3027
US                1033
U.S.               237
United States      220
                  ...
denmark              1
Nigeria              1
ss                   1
Nigeria              1
Burma                1
Name: count, Length: 118, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [61]:
# Replace them all in-place with 'US'.
selected = ["United States", "USA", "U.S.", "U.S.A"]
df_salary_tech.loc[df_salary_tech["country"].isin(selected), "country"] = "US"

Have a look at the count of each unique country again now.

In [62]:
# Count again.

df_salary_tech["country"].value_counts()

country
US                          7797
United States                220
United States of America     180
USA                          164
Usa                          161
                            ...
denmark                        1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, Length: 114, dtype: int64

Did you notice anything interesting?

In [63]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [64]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [66]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

gb = df_salary_tech.groupby("country")

try:
  gb["salary"].mean()
except:
  print("Cannot get mean() of str")

Cannot get mean() of str

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [ ]:
# Fix it in-place.

df_salary_tech["salary"] = pd.to_numeric(df_salary_tech["salary"], errors = "coerce")
df_salary_tech.dropna(subset="salary", inplace=True)
df_salary_tech["salary"] = df_salary_tech["salary"].astype(int)

Let’s try that again.

In [ ]:
# Try it again. Yeah!
gb = df_salary_tech.groupby("country")
summary = gb["salary"].agg(["min", "max", "mean"])

print(summary.loc["US"])

min     0.000000e+00
max     2.600000e+06
mean    1.038251e+05
Name: US, dtype: float64

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [ ]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
import datetime as dt
df_salary_tech["timestamp"] = pd.to_datetime(df_salary_tech["timestamp"])


selected_year = [2021,2022]

df_salary_tech = df_salary_tech[df_salary_tech["timestamp"].dt.year.isin(selected_year)]
df_salary_tech

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
3,2021-04-27 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,US,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
8,2021-04-27 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
10,2021-04-27 11:03:03,25-34,Nonprofits,Office Manager,NaN,"47,500",0.0,USD,NaN,NaN,US,NaN,"Boston, MA",5-7 years,5-7 years,College degree,Woman,White
20,2021-04-27 11:03:24,25-34,Health care,Data Programmer Analyst,NaN,"74,000",0.0,USD,NaN,NaN,US,Pennsylvania,Philadelphia,5-7 years,5-7 years,Master's degree,Woman,White
21,2021-04-27 11:03:24,35-44,Nonprofits,Program Coordinator & Assistant Editor,NaN,"50,000",NaN,USD,NaN,NaN,US,NaN,Atlanta,5-7 years,2 - 4 years,PhD,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27914,2022-12-11 10:08:24,25-34,Health care,Pharmacist,NaN,151257,9075.0,USD,NaN,NaN,US,Colorado,Colorado,5-7 years,8 - 10 years,"Professional degree (MD, JD, etc.)",Woman,NaN
27915,2022-12-13 18:21:14,25-34,Computing or Tech,Business Development Director,NaN,111000,30000.0,USD,NaN,NaN,US,California,Costa Mesa,5-7 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin, White"
27916,2022-12-17 07:48:12,25-34,Nonprofits,Director of Content and Brand,NaN,95000,5000.0,USD,NaN,NaN,US,Maryland,Rockville,11 - 20 years,5-7 years,College degree,Woman,Asian or Asian American
27919,2022-12-22 15:46:39,35-44,Nonprofits,Director of Government Affairs,NaN,89000,1000.0,USD,NaN,NaN,US,Missouri,St. Louis,11 - 20 years,11 - 20 years,Master's degree,Man,White
27921,2022-12-29 07:54:18,55-64,Health care,Physical therapist assistant,Home health,62400,NaN,USD,NaN,NaN,Usa,Colorado,Denver,31 - 40 years,21 - 30 years,Some college,Woman,White

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)